# Generated by Django 4.2.6 on 2023-11-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ningsih', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={'verbose_name_plural': 'Detail Transaksi'},
        ),
        migrations.AlterModelOptions(
            name='transaksi',
            options={'verbose_name_plural': 'Data Transaksi'},
        ),
    ]
