# Generated by Django 4.2.6 on 2023-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovita', '0002_alter_kategori_options_alter_kontak_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
    ]
